SELECT COUNT(CLIENTID) AS COUNT_CLIENT FROM CLIENT;

SELECT SUM(BILLAMOUNT) AS SUM_BILAM FROM BILL;

SELECT
    MANAGERID AS ID,
    COUNT(MANAGERID) AS COUNT_MNGR
FROM CLIENT
GROUP BY MANAGERID;

SELECT
    MANAGERID AS ID,
    COUNT(MANAGERID) AS COUNT_MNGR
FROM CLIENT
GROUP BY MANAGERID
ORDER BY COUNT(MANAGERID) ASC;
