name:  SQLCodeConvention 
on: 
 push: 
   branches: tasks-of-laboratory-work-10
jobs: 
 SQLFluffValidate:
   runs-on: ubuntu-latest
   steps: 
     - name: Check repo
       uses: "actions/checkout@v3"
     - name: start sql linter 
       run: 
         pip install sqlfluff
         sqlfluff lint -d oracle $GITHUB_WORKSPACE/9-AnalyticFunctions/*.sql
